/* Read only. No rows means the expected installation and private permissions are present. */
WITH required(signature) AS (VALUES ('public.inventory_list_receipt_suppliers_v1()'),('public.inventory_save_receipt_supplier_v1(uuid,text,text)'),('public.inventory_deactivate_receipt_supplier_v1(uuid)'),('public.inventory_receipt_metadata_v1(text,uuid[])'),('public.inventory_create_receipts_v1(text,jsonb,uuid)'),('public.inventory_update_receipt_v1(text,uuid,date,uuid,numeric,numeric,text,text,uuid,text)'),('public.inventory_adjust_receipt_v1(text,uuid,numeric,date,numeric,text,uuid)'),('public.inventory_cancel_receipts_v1(text,uuid[])'))
SELECT 'missing_rpc' AS problem,signature AS detail FROM required WHERE to_regprocedure(signature) IS NULL
UNION ALL SELECT 'anonymous_rpc',signature FROM required WHERE has_function_privilege('anon',to_regprocedure(signature),'EXECUTE')
UNION ALL SELECT 'missing_client_rpc',signature FROM required WHERE NOT has_function_privilege('authenticated',to_regprocedure(signature),'EXECUTE')
UNION ALL SELECT 'missing_column',t||'.'||c FROM (VALUES('inventory_transactions'),('phoi_transactions')) x(t) CROSS JOIN (VALUES('source_kind'),('supplier_id'),('supplier_code_snapshot'),('supplier_name_snapshot'),('created_by_name_snapshot')) y(c) WHERE NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=t AND column_name=c)
UNION ALL SELECT 'missing_guard',t FROM (VALUES('inventory_transactions'),('phoi_transactions')) x(t) WHERE NOT EXISTS(SELECT 1 FROM pg_trigger g JOIN pg_class r ON r.oid=g.tgrelid JOIN pg_namespace n ON n.oid=r.relnamespace WHERE n.nspname='public' AND r.relname=t AND g.tgname='zz_receipt_source_guard' AND g.tgenabled='O')
UNION ALL SELECT 'private_table_writable',t FROM (VALUES('inventory_receipt_supplier_codes'),('inventory_receipt_source_audit'),('inventory_receipt_requests')) x(t) WHERE has_table_privilege('authenticated','public.'||t,'INSERT,UPDATE,DELETE')
UNION ALL SELECT 'source_guard_wrong_rights','Must use invoker rights to block direct client writes' WHERE EXISTS(SELECT 1 FROM pg_proc WHERE oid=to_regprocedure('public.inventory_guard_receipt_source_v1()') AND prosecdef);
