// Generated by scripts/test-inventory-receipt-sources.mjs --write-artifacts from the installed migration in temporary PostgreSQL.
// Scoped to receipt sources; does not claim to describe the full production schema.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type ReceiptSourceColumns = {
  source_kind: string | null;
  supplier_id: string | null;
  supplier_code_snapshot: string | null;
  supplier_name_snapshot: string | null;
  created_by_name_snapshot: string | null;
};

export type ReceiptFunctions = {
  inventory_adjust_receipt_v1: {
    Args: { p_kind: string | null; p_transaction_id: string | null; p_target_qty: number | null; p_tx_date: string | null; p_unit_cost: number | null; p_note: string | null; p_request_id: string | null };
    Returns: Json;
  };
  inventory_can_manage_receipt_suppliers_v1: {
    Args: Record<string, never>;
    Returns: boolean;
  };
  inventory_cancel_receipts_v1: {
    Args: { p_kind: string | null; p_transaction_ids: string[] | null };
    Returns: Json;
  };
  inventory_create_receipts_v1: {
    Args: { p_kind: string | null; p_rows: Json | null; p_request_id: string | null };
    Returns: Json;
  };
  inventory_deactivate_receipt_supplier_v1: {
    Args: { p_supplier_id: string | null };
    Returns: undefined;
  };
  inventory_list_receipt_suppliers_v1: {
    Args: Record<string, never>;
    Returns: { id: string | null; code: string | null; name: string | null; is_active: boolean | null }[];
  };
  inventory_receipt_metadata_v1: {
    Args: { p_kind: string | null; p_transaction_ids: string[] | null };
    Returns: { id: string | null; source_kind: string | null; supplier_id: string | null; supplier_code_snapshot: string | null; supplier_name_snapshot: string | null; created_by_name_snapshot: string | null }[];
  };
  inventory_save_receipt_supplier_v1: {
    Args: { p_supplier_id: string | null; p_code: string | null; p_name: string | null };
    Returns: string;
  };
  inventory_update_receipt_v1: {
    Args: { p_kind: string | null; p_transaction_id: string | null; p_tx_date: string | null; p_product_id: string | null; p_qty: number | null; p_unit_cost: number | null; p_note: string | null; p_source_kind: string | null; p_supplier_id: string | null; p_source_reason?: string | null };
    Returns: Json;
  };
};
